add footer for all pages
acm-ucr/ucr-hearts-website pull request #34
Opened 2024-10-13 09:58 UTC by minhhdtran

2024-10-13 10:04 UTC, minhhdtran commented
![hearts_footer](https://github.com/user-attachments/assets/e0db2a36-0114-4d7d-94f3-4cc50f2554b8)

2024-10-15 22:16 UTC, qhgill requested changes
overall looks good, just change to use tailwind's default white to reduce redundancies

2024-10-15 22:16 UTC, qhgill commented on tailwind.config.ts
> +        white: "#FFFFFF",
no need to add this, just use text-white or bg-white whenever you need

2024-10-17 19:57 UTC, qhgill commented on tailwind.config.ts
> +        white: "#FFFFFF",
disregard, temporary fix for a problem I have to fix later

2024-10-17 19:58 UTC, qhgill approved these changes

2024-10-17 19:58 UTC, merged