implemented AboutTitle.tsx
acm-ucr/ucr-hearts-website pull request #35
Opened 2024-10-15 08:11 UTC by catheiwu

<img width="1440" alt="Screenshot 2024-10-15 at 1 07 14 AM" src="https://github.com/user-attachments/assets/092f21ce-adee-4aa6-82c7-0794e82a4a68">

2024-10-15 08:13 UTC, catheiwu commented
I was wondering how to get the required font style for the "About Us" text.

2024-10-15 23:01 UTC, qhgill requested changes
Looks great! just use the hearts-brown color for the title.

2024-10-15 23:01 UTC, qhgill commented on tailwind.config.ts
> +        lightBrown: "#897165",
just use the regular brown for the title and remove the extra color

2024-10-17 06:45 UTC, catheiwu commented
<img width="722" alt="Screenshot 2024-10-16 at 11 45 14 PM" src="https://github.com/user-attachments/assets/59aada37-17c3-4819-9c98-2e0a30a24d5f">
Changed font color to just regular brown

2024-10-17 20:02 UTC, qhgill approved these changes
looks good!

2024-10-17 20:03 UTC, merged