inegishi/mobile
acm-ucr/ucr-hearts-website pull request #80
Opened 2024-11-12 04:34 UTC by inegishi

Mobile version:
![Screenshot 2024-11-11 202821](https://github.com/user-attachments/assets/ab24c70b-4510-48cd-bd72-b7c834e9a6ef)

2024-11-14 00:22 UTC, qhgill requested changes
looks good for smaller screens like iPad/laptop but mobile screens end up bugging out: 
![image](https://github.com/user-attachments/assets/df62b50c-7fb1-4b18-b646-bde28fc2c76b)
you can try changing the cards to align vertically instead of horizontally and see if that makes things easier.

2024-11-14 00:22 UTC, qhgill commented on src/components/events/EventCard.tsx
> +      <p className="w-[90%] text-[0.8vw] font-extralight text-hearts-brown md:text-[1vw]">
md: should go before the old formatting you want to keep for desktop, new mobile formatting has no prefix

2024-11-14 05:16 UTC, inegishi commented
![image](https://github.com/user-attachments/assets/eb242b78-2648-4b11-a055-aecd8f43f125)

Its now in a column for mobile screens.

2024-11-15 00:02 UTC, qhgill approved these changes

2024-11-15 00:02 UTC, merged