improve mobile response for description.tsx and mentorship.tsx
acm-ucr/ucr-hearts-website pull request #92
Opened 2024-11-21 04:46 UTC by inegishi

2024-11-21 04:48 UTC, inegishi commented
![image](https://github.com/user-attachments/assets/0de50f41-74da-4a33-95d3-a0e35193ff4e)

2024-11-22 03:24 UTC, qhgill requested changes
when checking for mobile make sure the page still looks uniform, should match components above, if you need help let me know.

2024-11-22 03:24 UTC, qhgill commented on src/components/about/Description.tsx
> +      <p className="mt-[2%] w-[60%] font-hearts text-[3vw] font-light text-hearts-brown lg:text-[1.8vw]">
check experience and todos components in about section and try to match width/text size

2024-11-24 04:50 UTC, inegishi commented
![Screenshot 2024-11-23 204833](https://github.com/user-attachments/assets/4ccd9316-24b8-4146-b89f-eb20a05ac32b)

2024-12-01 07:27 UTC, qhgill approved these changes

2024-12-01 07:27 UTC, merged